### ISSUE TITLE
Getting Errors in hooks  HOOK-ERROR in after_step: TypeError: Object of type _PresenceSentinel is not JSON serializable

### ISSUE THREAD

**Issue by chandransh-sharma** [reportportal/examples-python#1]
Description: This issue is occuring while using behave agent with reportportal. Can anyone let me know how can this be resolved or is it a genuine bug in the behave agent library.

Issue -`HOOK-ERROR in after_step: TypeError: Object of type _PresenceSentinel is not JSON serializable
`
Logs:  

> Traceback (most recent call last):
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/behave/model.py", line 1329, in run
>           match.run(runner.context)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/behave/matchers.py", line 98, in run
>           self.func(context, *args, **kwargs)
>         File "tests/features/steps/example_steps.py", line 6, in step_impl
>           context.log.info('Behave is installed.')
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1477, in info
>           self._log(INFO, msg, args, **kwargs)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/logs/__init__.py", line 79, in _log
>           self.handle(record)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1634, in handle
>           self.callHandlers(record)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
>           hdlr.handle(record)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 968, in handle
>           self.emit(record)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/logs/__init__.py", line 177, in emit
>           rp_client.log(
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/client.py", line 765, in log
>           return self._log(self._log_batcher.append(rp_log))
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/_internal/logs/batcher.py", line 75, in append
>           return self._append(log_req.multipart_size, log_req)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/core/rp_requests.py", line 453, in multipart_size
>           return RPRequestLog._multipart_size(self.payload, self.file)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/core/rp_requests.py", line 443, in _multipart_size
>           size = helpers.calculate_json_part_size(payload)
>         File "/Users/csharm/PycharmProjects/Test_Reports/venv/lib/python3.10/site-packages/reportportal_client/helpers.py", line 357, in calculate_json_part_size
>           size = len(json.dumps(json_dict))
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
>           return _default_encoder.encode(obj)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
>           chunks = self.iterencode(o, _one_shot=True)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
>           return _iterencode(o, 0)
>         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
>           raise TypeError(f'Object of type {o.__class__.__name__} '
>       TypeError: Object of type _PresenceSentinel is not JSON serializable
>       
>       Captured stdout:
>       HOOK-ERROR in after_step: TypeError: Object of type _PresenceSentinel is not JSON serializable
> 
> HOOK-ERROR in after_scenario: TypeError: Object of type _PresenceSentinel is not JSON serializable
>     When we implement 5 tests          # None
>     Then behave will test them for us! # None

**Comment by Pink-Bumblebee** [comment]
@chandransh-sharma , maybe documentation will be helpful for you: https://github.com/reportportal/agent-python-behave. From the first sight, it looks like you've missed some parameters or trying to connect to wrong instance.
BTW, have you tried to implement example from this repo? Everything worked fine?

**Comment by chandransh-sharma** [comment]
> @chandransh-sharma , maybe documentation will be helpful for you: https://github.com/reportportal/agent-python-behave. From the first sight, it looks like you've missed some parameters or trying to connect to wrong instance. BTW, have you tried to implement example from this repo? Everything worked fine?

Hi I have gone through the documentation and tried the example from the above. Still getting same error. I think while trying to send data there is an issue with its format. Below is the screenshot of my report portal parameters. I have placed the generated api key for test as well as the localhost url. Can you give me some pointers for debugging which can help resolve this error.

<img width="1383" alt="image" src="https://github.com/reportportal/examples-python/assets/135574457/5bc42ceb-0740-4f64-ab1d-4e0516426ea4">

<img width="1383" alt="image" src="https://github.com/reportportal/examples-python/assets/135574457/66ccbd6a-a4f4-42e7-ab6d-b0077a19ee45">

**Comment by chandransh-sharma** [comment]
@Pink-Bumblebee Thank you. Issue is now resolved. The last api key had some issues. After creating new api key it worked . I will close this.
